### ISSUE TITLE
LineMOD Dataset

### ISSUE THREAD

**Issue by albertmend** [zakharos/DPOD#1]
Hello,

Are you planning to release the full dataset ready for training? If not, could you gave some recommendations on how to preprocess the original LineMOD dataset and obtain the needed files for training?
Thank you,

Dennis

**Comment by mGagalong** [comment]
Hello,

Could you release  pretrained network location? 
Thank you.

Gagalong

**Comment by zakharos** [comment]
Hey Dennis and Gagalong! We don't plan to release the full dataset, but we will upload the pretrained networks and also the instructions on how to generate the training data later this year. Thanks!

**Comment by mGagalong** [comment]
Thank you!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zakharos/DPOD"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 凌晨2:21
收件人:&nbsp;"zakharos/DPOD"<DPOD@noreply.github.com&gt;;
抄送:&nbsp;"嘎嘎龙"<616100392@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zakharos/DPOD] LineMOD Dataset (#1)





 
Hey Dennis and Gagalong! We don't plan to release the full dataset, but we will upload the pretrained networks and also the instructions on how to generate the training data later this year. Thanks!

**Comment by albertmend** [comment]
Thank you!
