### ISSUE TITLE
Reproducibility issue of the DPOD’s refinement network

### ISSUE THREAD

**Issue by sh8** [zakharos/DPOD#5]
Hi Zakharov!

Thank you for making your work publicly available. I'm trying to reproduce the result of DPOD refiner by following what the paper says, however, my scores still have the large gap from the reported one.

As the explanation of the network architecture lacks some details, could you please answer the following questions to reproduce your paper's result?

- What kind of ResNet are you using? (ResNet18 or ResNet50?)
- XY location given to the network is the center of bounding box or projection of the center of a 3D model?
- How do you extract the feature vector from E2? Simply using max pooling?
- Could you let me know the algorithm of what this line says? `Weights of the fully connected layers are initialized in such a way that for the 0th iteration the network just outputs the input pose, `
-  Regarding this paragraph `The first layer of the rotation regression head takes the feature vector f produced by ResNet and adds four values, which are the quaternion representing an initial rotation. The second layer takes the output of the previous one, stacks with the initial quaternion and outputs the final rotation`, the quaternion is fed into both the first and second layers? What does `adds four values` mean here? (looks like concatenation is correct)

Thanks,
Shun

**Comment by albertmend** [comment]
@sh8 Were you able to reproduce the results without the refinement network?

**Comment by sh8** [comment]
@albertmend 
I haven't done experiments without the refinement network yet, but will do soon 👍 
Let you know if I can reproduce the result!
