### ISSUE TITLE
Bug in the ADD(-S)-0.1d, 0.3d, and 0.5d metric calculation?

### ISSUE THREAD

**Issue by sh8** [zakharos/DPOD#6]
Based on the definition of the ADD(-S) metric, I'd say the following lines in `DPOD/pipelines/test.py` should be
```
add_10 = count_add_10 / len(testloader)
add_30 = count_add_30 / len(testloader)
add_50 = count_add_50 / len(testloader)
```
not,
```
add_10 = count_add_10 / n_detected_correctly
add_30 = count_add_30 / n_detected_correctly
add_50 = count_add_50 / n_detected_correctly
```

Could you please check if my understanding is correct at leisure?

https://github.com/zakharos/DPOD/blob/b33773bac5b3ce13b2e9fe457c908dfac0a4f275/pipelines/test.py#L203
https://github.com/zakharos/DPOD/blob/b33773bac5b3ce13b2e9fe457c908dfac0a4f275/pipelines/test.py#L204
https://github.com/zakharos/DPOD/blob/b33773bac5b3ce13b2e9fe457c908dfac0a4f275/pipelines/test.py#L205

**Comment by zakharos** [comment]
Hi! Thank you for your comment! We indeed measure the accuracy of pose estimation as the percentage of correctly estimated poses. This is also mentioned in the paper (check "7.2. Evaluation Metrics"). However, our results for the average recall of ADD could be found in the paper by Wang and Manhardt et al. [Self6D: Self-Supervised Monocular 6D Object Pose Estimation](http://campar.in.tum.de/pub/wang2020self6d/wang2020self6d.pdf).

**Comment by sh8** [comment]
Thank you for answering the question! I see. Since some of other methods such as PVNet and PoseCNN consider all poses, does this mean that we can't fairly compare the results of ADD(-S) among them?

**Comment by sh8** [comment]
Is it possible to provide me with the average recall of ADD(-S) on the Occlusion Linemod dataset?
