### ISSUE TITLE
GT annotations for LINEMOD

### ISSUE THREAD

**Issue by albertmend** [zakharos/DPOD#7]
Hello,

Could you provide gt.yml files for the rest of the objects in LINEMOD please?
Thank you,

Dennis Mendoza

**Comment by kolnol** [comment]
Hi Dennis, 

you can find LINEMOD dataset with annotations on BOP challenge website:
https://bop.felk.cvut.cz/datasets/

You can also find there other datasets, such as LINEMOD OCCLUDED, YCB-V etc.

**Comment by albertmend** [comment]
@kolnol Thank you so much for the information!
